# Use for testing only

version: '3.8'

services:
  users.mongo:
    image: mongo
    restart: always
    container_name: users.mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 12345678
      MONGO_INITDB_DATABASE: users
    ports:
      - "27017:27017"
    volumes:
      - mongo.users:/data/db

    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/users --quiet
      interval: 10s
      timeout: 10s
      retries: 5

    networks:
      - users.network

  users.mongo.ui:
    image: mongo-express
    restart: always
    container_name: users.mongo.ui
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://admin:12345678@users.mongo:27017/
    depends_on:
      - users.mongo
    networks:
      - users.network

  users.cache:
    image: redis:6.2-alpine
    restart: always
    container_name: users.cache
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass 12345678
    volumes:
      - redis.users:/data
    networks:
      - users.network

networks:
  users.network:
    driver: bridge

volumes:
  mongo.users:
  redis.users:
